name: flask workflow

on:
    push:
        branches:
            main
    pull:
        branches:
            main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"

        - name: install dependencies
          run: |
           pip installflask
           pip install pytest

        - name: run test
          run: |
           pytest

        - name: docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets. DOCKER_PASSWORD}}
        
        - name: build docker image
          run: |
            docker build -t jackrice/myflask-app:latest .

        - name: push to docker hub
          run: |
           docker push jackrice/myflask-app:latest

            

